### ISSUE TITLE
Debugging using Developer Tools.

### ISSUE THREAD

**Issue by armoucar** [ghinda/jotted#33]
Hello @ghinda,

is it a jotted restriction being able to debug (using devtools) javascript files? By javascript files, I mean the one we pass to jotted as a parameter.

Thanks!

**Comment by ghinda** [comment]
Hi,

That's right. Jotted loads the file content and inserts it in the iframe inline.

So instead of `<script src="file.js"></script>`, you get `<script>${file.js_content}</script>`.
It needs to do this so the plugins can modify the content (eg. coffescript, etc.).

Here's the code:
https://github.com/ghinda/jotted/blob/master/src/core.js#L168-L183
