### ISSUE TITLE
Splitted pane to show both code and result.

### ISSUE THREAD

**Issue by lapanoid** [ghinda/jotted#5]
I think that splitted pane to show both code and result will be awesome as user could edit and see result at same time than.
http://joxi.ru/brR6YzNFQBj4lr.png

**Comment by ghinda** [comment]
Just wanted to let you know I'm working on a theme similar to the JSBin layout. It will be probably be ready early next week.

**Comment by lapanoid** [comment]
Great news, thanks!
26 янв. 2016 г. 6:22 PM пользователь "Ionut Colceriu" <
notifications@github.com> написал:

**Comment by ghinda** [comment]
Released `1.1.0` with the new *bin* theme, similar to the JSBin layout. You can't toggle the file types (html, css, js) on and off, like you can on JSBin, because they act like tabs here.

The editors are visible only for the file types you have, or if you use the `showBlank` option. 

Here's a demo:
https://ghinda.net/jotted/demos/theme-bin.html

**Comment by lapanoid** [comment]
Thanks! You are awesome, man :beers: :+1:
